name: Build & Publish to Spacemaven Repository

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

env:
  SPACEPORT_READY: true

jobs:
  build-and-publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            tasks: publishLinuxTargetsToSpacemavenNativeRepository
            cc: cc
            cxx: c++
          - os: windows-latest
            tasks: publishWindowsTargetsToSpacemavenNativeRepository
            cc: cl
            cxx: cl
          - os: macos-latest
            tasks: publishMacosTargetsToSpacemavenNativeRepository
            cc: cc
            cxx: c++
    name: Build and Publish
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
          validate-wrappers: true
      - name: Setup Publishing Properties
        run: |
          echo "spacemaven.user=${{ secrets.SPM_USERNAME }}" >> gradle.properties
          echo "spacemaven.key=${{ secrets.SPM_KEY }}" >> gradle.properties
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.4.1
        if: matrix.os == 'windows-latest'
      - name: Grab Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
      - name: Build Project
        run: ./gradlew build
      #- name: List files
      #  if: matrix.os == 'windows-latest'
      #  run: dir spaceport\glfw\build\cmake\sharedLibrary\debug\windows\x86-64\src
      - name: Publish Project
        if: env.SPACEPORT_READY
        run: ./gradlew ${{ matrix.tasks }}
  finalize-publish:
    needs: build-and-publish
    name: Finalize Publication
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
          validate-wrappers: true
      - name: Setup Publishing Properties
        run: |
          echo "spacemaven.user=${{ secrets.SPM_USERNAME }}" >> gradle.properties
          echo "spacemaven.key=${{ secrets.SPM_KEY }}" >> gradle.properties
      - name: Publish Project
        if: env.SPACEPORT_READY
        run: ./gradlew publishCommonArtifactsToSpacemavenNativeRepository
